name: Build and Deploy .NET API

on:
  push:
    branches: [ "develop" ]
  # Cho phép trigger thủ công
  workflow_dispatch:

jobs:
  #############################
  # JOB 1: BUILD & TEST       #
  #############################
  build:
    runs-on: ubuntu-latest
    outputs:
      # Xuất ra tên image để job sau sử dụng
      image_name: ${{ steps.docker_meta.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      # (Tùy chọn) Thêm bước chạy Unit Test ở đây
      # - name: Run tests
      #   run: dotnet test --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          # Tạo tag: latest và tag theo mã commit SHA
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  ####################################
  # JOB 2: DEPLOY TO PRODUCTION    #
  ####################################
  deploy:
    # Job này chỉ chạy sau khi job 'build' thành công
    needs: build
    runs-on: ubuntu-latest
    
    # Thêm môi trường để có thể cấu hình phê duyệt thủ công trong Settings
    environment:
      name: production
      url: https://todo-list-api-2.nhanvathucau.io.vn

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml" # Tên file trong repo
          target: "${{ secrets.DOCKER_DEPLOY_PATH }}" # Thư mục đích trên VPS
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Di chuyển tới thư mục triển khai
            # mkdir -p ${{ secrets.DOCKER_DEPLOY_PATH }}
            cd ${{ secrets.DOCKER_DEPLOY_PATH }}
            
            # Ghi tên image từ job build vào file .env để docker-compose đọc
            echo "IMAGE_TAG=${{ needs.build.outputs.image_name }}" > .env

            # Đăng nhập vào Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            
            # Kéo image mới nhất và khởi động lại dịch vụ
            docker-compose pull
            docker-compose up -d --remove-orphans
